config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :questions do
    resources :answers, only: [:create, :new, :destroy, :update, :edit]
  end
  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  resources :users
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user


  validates :user_id, presence: true
  validates :question_id, presence: true
  validates :answer, length: {minimum: 50}

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers, dependent: :destroy


  validates :user_id, presence: true
  validates :title, length: {minimum: 40}
  validates :question, length: {minimum: 150}

end

app/models/users.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers

  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash['provider'], hash['uid'])
  end

  def self.create_from_hash(hash)
    User.create(:user => user, :uid => hash['uid'], :provider => hash['provider'], :name => hash['user_name'])
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
   @question = Question.find(params[:question_id])

    @answer = Answer.new(answer_params)

    @answer.question = @question

    if @answer.save
      redirect_to question_path(@question)
    else
      @answers = @question.answers.all
      render 'questions/show'
    end
  end

  def new
    @answer = Answer.new()
  end

  def destroy
    question = Question.find(params[:question_id])
    @answers = question.answers.all

  end

  def update
    @answer =  Answer.find(params[:id])
    if @answer.update(is_best: true)
      Answer.where('NOT id=?', params[:id].to_i).update_all(is_best: false)

      redirect_to question_path(@answer.question)
    else

    end
  end

  private

  def answer_params
    params.require(:answer).permit(:user_id, :answer,:question_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def signed_in?
    !!current_user
  end

  helper_method :current_user, :signed_in?

  def current_user=(user)
    @current_user = user
    session[:user_id] = user.id
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all

  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.all.order(is_best: :desc)

    @answer = Answer.new
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def new
    @question =  Question.new()
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question =  Question.find(params[:id])
    if @question.update(question_params)
     redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])

    if @question.destroy
      redirect_to questions_path
    else
      render :show
    end

  end

  private

  def question_params
    params.require(:question).permit(:title, :question, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env['rack.auth']
    binding.pry
    unless User.find_from_hash(auth)
      # Create a new user or add an auth to existing user, depending on
      # whether there is already a user signed in.
      @user =User.create_from_hash(auth, current_user)
    end
    # Log the authorizing user in.
    self.current_user = @user

    render :text => "Welcome, #{current_user.name}."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= form_for @question do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %>

  <%= f.label :question %>:
  <%= f.text_field :question %>

  <%= f.submit %>

<% end %>

app/views/questions/index.html.erb
<a href= '/auth/:provider/callback'> Login </a>

<ul>
  <% @questions.each do |question| %>
  <h3><%= link_to(question.title, question_path(question)) %></h3>
  <li><%= question.question %></li>
  <% end %>
</ul>

app/views/questions/new.html.erb
Ask a Question

<%= form_for @question do |f| %>
  <%= f.label :title %>:
  <%= f.text_field :title %>

  <%= f.label :question %>:
  <%= f.text_field :question %>

  <%= f.label :user_id %>:
  <%= f.text_field :user_id %>

  <%= f.submit %>

<% end %>



<!--  I set user up awkwardly; will need to put in manual user #s until I implement authentification
 -->

app/views/questions/show.html.erb
<p><%= @question.title %></p>
<br>
<p><%= @question.question %></p>

<ul>
    <% @answers.each do |answer| %>

    <li>
    <%= answer.answer %> <%= link_to("Vote Best!", question_answer_path(@question,answer), action: :update, method: :patch) %>
    </li>
    <%= answer.is_best == true ? "Best answer above!" : nil %>
    <% end %>
</ul>


<%= form_for [@question, @answer] do |f| %>
  <% f.label :user_id %>:
  <%= f.text_field :user_id %><br>

  <%= f.label :answer %>:
  <%= f.text_field :answer %> <br>

  <%= f.submit %>
<% end %>

<%= link_to("Delete", question_path(@question), method: :delete) %>